### ISSUE TITLE
maintainance

### ISSUE THREAD

**Issue by nerdoc** [syse-i/django-component-tags#10]
Hi, I just wanted to ask how you plan to support d-c-t. I think it's a great project, and I'd like to use it in a bigger open source project. All the other projects I found were worse or unmaintained.
I am using BS5, and even would be willing to contribute to a django-component-tags-bootstrap5 library ;-)

**Comment by david-sosa-valdes** [comment]
Hello Chris!

Really happy to hear your feedback. Please feel free to contribute to the bootstrap library and we will merge your pull requests.

Also to answer your question, we are not working on any plans to support this project more than we did so far because it accomplishes our personal goals, but we are willing to accept any kind of pull requests that the dev community think it could fit in here. 

If you could please elaborate on this "feature", it could be useful so we can establish some dev goals to implement it.

Thank you

**Comment by nerdoc** [comment]
With "this feature" you mean "django-component-tags-bootstrap5"? Because It wouldn't make much sense to make a PR to this repo here for  bs5 components. tailwind has it's own, as yo ustate in the README, and I think it would be best to create another package for d-c-t-bs5.

I don't have too much spare time, but I need bs5 components anyway, so instead of implementing them in my project, I could maybe externalize them into a separate one.

**Comment by nerdoc** [comment]
For my maintainance question here - I just wanted to know if you plan to abandon that project in the next time or leave it unmaintained.. If you tell me you need that for yourself for some time, that's enough for me.

**Comment by david-sosa-valdes** [comment]
> With "this feature" you mean "django-component-tags-bootstrap5"? Because It wouldn't make much sense to make a PR to this repo here for bs5 components. tailwind has it's own, as yo ustate in the README, and I think it would be best to create another package for d-c-t-bs5.
> 
> I don't have too much spare time, but I need bs5 components anyway, so instead of implementing them in my project, I could maybe externalize them into a separate one.

Yes of course, i did not understand the d-c-t meaning before. I could be great to create your own theme library similar to the "tailwind" library that we made.

**Comment by david-sosa-valdes** [comment]
> For my maintainance question here - I just wanted to know if you plan to abandon that project in the next time or leave it unmaintained.. If you tell me you need that for yourself for some time, that's enough for me.

We do not have any plans to abandon this library, because we use it for a couple of projects. We have it without changes 2 years from now because this library accomplishes our goals.  If you find any bug we will try our best to fix it ASAP, but we are a software company and we have deadlines, and sometimes it could take more time to fix something here.

I'm giving you a honest response, this is one of our open source libraries and we will do our best to respond in time. But we need everyone around here to help with everything that they can as well.

**Comment by nerdoc** [comment]
Thanks!
